### ISSUE TITLE
Deploy to Heroku failing with ArgumentError on Postgrex.Utils.parse_version/1

### ISSUE THREAD

**Issue by fdbeirao** [mustafaturan/shield#61]
I am trying the Deploy to Heroku button, and on the `Run scripts & scale dynos` step I get the following error:

```
[31m
14:14:03.130 [error] GenServer #PID<0.186.0> terminating
** (ArgumentError) argument error
    (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
    (postgrex) lib/postgrex/protocol.ex:641: Postgrex.Protocol.bootstrap_send/6
    (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
Last message: nil
State: Postgrex.Protocol
[0m** (exit) exited in: :gen_server.call(#PID<0.186.0>, {:checkout, #Reference<0.0.1.1772>, true, :infinity}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
            (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
            (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
            (postgrex) lib/postgrex/protocol.ex:641: Postgrex.Protocol.bootstrap_send/6
            (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
            (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
            (connection) lib/connection.ex:622: Connection.enter_connect/5
    (db_connection) lib/db_connection/poolboy.ex:112: DBConnection.Poolboy.checkout/3
    (db_connection) lib/db_connection.ex:920: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1133: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:93: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:193: Ecto.Adapters.SQL.query!/5
```

These were the parameters I specified:

![image](https://user-images.githubusercontent.com/6030940/36208835-5c00437a-119a-11e8-95ff-80022f9fff4d.png)

This is the `build log`:

```
-----> Elixir app detected
-----> Checking Erlang and Elixir versions
       Will use the following versions:
       * Stack heroku-16
       * Erlang 19.0
       * Elixir 1.3.2 
-----> Will export the following config vars:
DATABASE_URL
POOL_SIZE
SECRET_KEY_BASE
SECRET_SIGNING_SALT
SENDGRID_API_KEY
SENDGRID_PASSWORD
SENDGRID_USERNAME
       * MIX_ENV=prod
-----> Stack changed, will rebuild
-----> Cleaning all cache to force rebuilds
-----> Fetching Erlang 19.0
-----> Installing Erlang 19.0 (changed)
-----> Fetching Elixir v1.3.2 for OTP 19
-----> Installing Elixir v1.3.2 (changed)
-----> Installing Hex
* creating /app/.mix/archives/hex-0.17.3
-----> Installing rebar
* creating /app/.mix/rebar
* creating /app/.mix/rebar3
-----> Executing pre compile: pwd
/tmp/build_1cb6682fe5215f90ad2c6a99c1443393/mustafaturan-shield-ba51f78
-----> Fetching app dependencies with mix
Resolving Hex dependencies...
Dependency resolution completed:
  authable 0.8.0
  bamboo 0.8.0
  certifi 0.7.0
  comeonin 3.0.1
  connection 1.0.4
  cors_plug 1.1.4
  cowboy 1.0.4
  cowlib 1.0.2
  db_connection 1.1.2
  decimal 1.4.1
  ecto 2.1.3
  elixir_make 0.4.0
  gettext 0.13.1
  hackney 1.6.5
  idna 1.2.0
  metrics 1.0.1
  mime 1.1.0
  mimerl 1.0.2
  phoenix 1.2.0
  phoenix_ecto 3.2.2
  phoenix_html 2.9.3
  phoenix_pubsub 1.0.1
  plug 1.3.0
  poison 2.2.0
  poolboy 1.5.1
  postgrex 0.13.3
  ranch 1.3.2
  secure_random 0.5.1
  shield_notifier 0.2.0
  ssl_verify_fun 1.1.1
* Getting phoenix (Hex package)
* Getting phoenix_ecto (Hex package)
* Getting gettext (Hex package)
* Getting cowboy (Hex package)
* Getting authable (Hex package)
* Getting shield_notifier (Hex package)
* Getting cors_plug (Hex package)
* Getting poison (Hex package)
* Getting plug (Hex package)
* Getting mime (Hex package)
* Getting bamboo (Hex package)
* Getting hackney (Hex package)
* Getting certifi (Hex package)
* Getting idna (Hex package)
* Getting metrics (Hex package)
* Getting mimerl (Hex package)
* Getting ssl_verify_fun (Hex package)
* Getting comeonin (Hex package)
* Getting ecto (Hex package)
* Getting postgrex (Hex package)
* Getting secure_random (Hex package)
* Getting connection (Hex package)
* Getting db_connection (Hex package)
* Getting decimal (Hex package)
* Getting poolboy (Hex package)
* Getting elixir_make (Hex package)
* Getting cowlib (Hex package)
* Getting ranch (Hex package)
* Getting phoenix_html (Hex package)
* Getting phoenix_pubsub (Hex package)
-----> Copying hex from /app/.mix/archives/hex-0.17.3
-----> Compiling
===> Compiling idna
===> Compiling mimerl
==> connection
Compiling 1 file (.ex)
Generated connection app
===> Compiling metrics
==> gettext
Compiling 1 file (.yrl)
Compiling 1 file (.erl)
Compiling 20 files (.ex)
Generated gettext app
==> ranch (compile)
Compiled src/ranch_transport.erl
Compiled src/ranch_app.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch_acceptors_sup.erl
Compiled src/ranch_server.erl
Compiled src/ranch_protocol.erl
Compiled src/ranch_sup.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch_tcp.erl
Compiled src/ranch_ssl.erl
Compiled src/ranch.erl
Compiled src/ranch_conns_sup.erl
==> poolboy (compile)
Compiled src/poolboy_worker.erl
Compiled src/poolboy_sup.erl
Compiled src/poolboy.erl
==> decimal
Compiling 1 file (.ex)
Generated decimal app
==> poison
Compiling 4 files (.ex)
Generated poison app
===> Compiling ssl_verify_fun
==> elixir_make
Compiling 1 file (.ex)
Generated elixir_make app
==> comeonin
mkdir -p priv
cc -g -O3 -Wall -I/app/.platform_tools/erlang/erts-8.0/include -Ic_src -fPIC -shared  c_src/bcrypt_nif.c c_src/blowfish.c -o priv/bcrypt_nif.so
Compiling 8 files (.ex)
Generated comeonin app
===> Compiling certifi
===> Package certifi-0.7.0 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /app/.cache/rebar3/hex/default/registry
===> Generating package index...
===> Writing index to /app/.cache/rebar3/hex/default/packages.idx
===> Compiling hackney
==> db_connection
Compiling 23 files (.ex)
Generated db_connection app
==> phoenix_pubsub
Compiling 12 files (.ex)
Generated phoenix_pubsub app
==> cowlib (compile)
Compiled src/cow_cookie.erl
Compiled src/cow_spdy.erl
Compiled src/cow_mimetypes.erl
Compiled src/cow_http_te.erl
Compiled src/cow_http_hd.erl
Compiled src/cow_date.erl
Compiled src/cow_qs.erl
src/cow_multipart.erl:392: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
Compiled src/cow_multipart.erl
Compiled src/cow_http.erl
==> cowboy (compile)
Compiled src/cowboy_middleware.erl
Compiled src/cowboy_sub_protocol.erl
Compiled src/cowboy_loop_handler.erl
Compiled src/cowboy_static.erl
Compiled src/cowboy_http_handler.erl
Compiled src/cowboy_spdy.erl
Compiled src/cowboy_app.erl
Compiled src/cowboy_http.erl
Compiled src/cowboy_bstr.erl
Compiled src/cowboy_handler.erl
Compiled src/cowboy.erl
Compiled src/cowboy_router.erl
Compiled src/cowboy_rest.erl
Compiled src/cowboy_req.erl
Compiled src/cowboy_websocket_handler.erl
Compiled src/cowboy_clock.erl
Compiled src/cowboy_websocket.erl
Compiled src/cowboy_sup.erl
Compiled src/cowboy_protocol.erl
==> mime
Compiling 1 file (.ex)
Generated mime app
==> plug
Compiling 44 files (.ex)
Generated plug app
==> phoenix_html
Compiling 8 files (.ex)
Generated phoenix_html app
==> bamboo
Compiling 21 files (.ex)
warning: function Phoenix.View.render_to_string/3 is undefined (module Phoenix.View is not available)
Found at 2 locations:
  lib/bamboo/phoenix.ex:271
  lib/bamboo/phoenix.ex:281
Generated bamboo app
==> shield_notifier
Compiling 5 files (.ex)
Generated shield_notifier app
==> cors_plug
Compiling 1 file (.ex)
Generated cors_plug app
==> phoenix
Compiling 60 files (.ex)
Generated phoenix app
==> postgrex
warning: the dependency :postgrex requires Elixir "~> 1.3.4 or ~> 1.4" but you are running on v1.3.2
Compiling 62 files (.ex)
Generated postgrex app
==> ecto
Compiling 69 files (.ex)
Compiling lib/ecto/query/builder/lock.ex (it's taking more than 10s)
Compiling lib/ecto/repo/queryable.ex (it's taking more than 10s)
Compiling lib/ecto/query/builder/filter.ex (it's taking more than 10s)
Compiling lib/ecto/repo/preloader.ex (it's taking more than 10s)
Compiling lib/ecto/migration/runner.ex (it's taking more than 10s)
Compiling lib/ecto/repo/schema.ex (it's taking more than 10s)
Compiling lib/ecto/migration/schema_migration.ex (it's taking more than 10s)
Compiling lib/ecto/adapters/postgres/connection.ex (it's taking more than 10s)
Generated ecto app
==> secure_random
Compiling 1 file (.ex)
Generated secure_random app
==> authable
Compiling 34 files (.ex)
warning: this check/guard will always yield the same result
  lib/authable/auth_strategies/header.ex:20
warning: this check/guard will always yield the same result
  lib/authable/auth_strategies/query_param.ex:18
warning: this check/guard will always yield the same result
  lib/authable/auth_strategies/query_param.ex:25
warning: this check/guard will always yield the same result
  lib/authable/auth_strategies/session.ex:20
Generated authable app
==> phoenix_ecto
Compiling 4 files (.ex)
Generated phoenix_ecto app
==> shield
Compiling 39 files (.ex)
Generated shield app
-----> Creating .profile.d with env vars
-----> Writing export for multi-buildpack support
-----> Executing post compile: pwd
/tmp/build_1cb6682fe5215f90ad2c6a99c1443393/mustafaturan-shield-ba51f78
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 76.1M
-----> Launching...
       Released v7
       https://••••••••••v-auth.herokuapp.com/ deployed to Heroku
```

There is an interesting warning in the build log:

```
==> postgrex
warning: the dependency :postgrex requires Elixir "~> 1.3.4 or ~> 1.4" but you are running on v1.3.2
```

**Comment by mustafaturan** [comment]
Thanks for reporting, when I have time, I will fix the bug
